# Antártida y Datos Maestros

Datos de estaciones en la Antártida y catálogo maestro de municipios.

**Endpoints cubiertos:**
- Datos meteorológicos de estaciones antárticas (BAE Juan Carlos I y BAE Gabriel de Castilla)
- Catálogo de municipios: listado completo, búsqueda por código y por nombre

In [1]:
# Instala el paquete (solo la primera vez)
!pip install -q aemetdata nest_asyncio

# -- API Key ---------------------------------------------------------
API_KEY = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjcGFjaGVjby5wZXJlbGxvQGdtYWlsLmNvbSIsImp0aSI6IjE2ZGQxZjJlLTJkMWYtNGI3NS1hYjQ0LWEzNTNhNmQyMjU0NiIsImlzcyI6IkFFTUVUIiwiaWF0IjoxNzY4MzgzMjcwLCJ1c2VySWQiOiIxNmRkMWYyZS0yZDFmLTRiNzUtYWI0NC1hMzUzYTZkMjI1NDYiLCJyb2xlIjoiIn0.4eP7KwIbUfdq91ZrcPYEwPhUgPN1sUhCyIZdrieHnc0"

# En Google Colab guarda tu clave como secreto con nombre AEMET_API_KEY
try:
    from google.colab import userdata
    API_KEY = userdata.get("AEMET_API_KEY") or API_KEY
except Exception:
    pass

import nest_asyncio; nest_asyncio.apply()
import pandas as pd
print(f"Listo. API key: {API_KEY[:8]}...")

[notice] A new release of pip is available: 23.2.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Listo. API key: eyJhbGci...

## 1. Datos de la Antártida

Estaciones antárticas españolas:
- `89064` = BAE Juan Carlos I (isla Livingston)
- `89070` = BAE Gabriel de Castilla (isla Decepción)

Las fechas deben ir en formato `AAAA-MM-DDTHH:MM:SSUTC`.

In [2]:
from aemetdata.antartida import datos_antartida
from aemetdata.utils.suport_functions import AemetError

try:
    datos = await datos_antartida(
        fecha_inicio="2024-01-01T00:00:00UTC",
        fecha_fin="2024-01-31T23:59:59UTC",
        identificacion="89064",
        api_keys=[API_KEY],
    )
    print(f"Registros obtenidos (BAE Juan Carlos I): {len(datos)}")
    display(pd.DataFrame(datos))
except AemetError as e:
    print(f"Endpoint no disponible: {e}")
    datos = []

Registros obtenidos (BAE Juan Carlos I): 4464

,identificacion,nombre,latitud,longitud,altitud,srs,altNieve,ddd,dddstd,dddx,...,temp,tmn,tmx,ts,tsb,tsmn,tsmx,vel,velx,qdato
0,89064,JCI Estacion meteorologica,-62.66325,-60.38959,12.0,WGS84,NaN,10.0,6.0,9.0,...,1.2,1.2,1.3,3.1,NaN,NaN,NaN,3.6,4.5,0.0
1,89064,JCI Estacion meteorologica,-62.66325,-60.38959,12.0,WGS84,NaN,25.0,6.0,33.0,...,1.2,1.1,1.2,3.0,NaN,NaN,NaN,3.6,4.4,0.0
2,89064,JCI Estacion meteorologica,-62.66325,-60.38959,12.0,WGS84,NaN,29.0,13.0,34.0,...,1.1,1.1,1.2,2.9,NaN,NaN,NaN,2.7,4.1,0.0
3,89064,JCI Estacion meteorologica,-62.66325,-60.38959,12.0,WGS84,NaN,36.0,10.0,22.0,...,1.1,1.1,1.2,2.9,NaN,NaN,NaN,2.4,3.4,0.0
4,89064,JCI Estacion meteorologica,-62.66325,-60.38959,12.0,WGS84,NaN,38.0,11.0,39.0,...,1.1,1.1,1.2,2.8,NaN,NaN,NaN,2.5,3.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4459,89064,JCI Estacion meteorologica,-62.66325,-60.38959,12.0,WGS84,0.0,124.0,17.0,123.0,...,1.5,1.4,1.6,3.6,NaN,NaN,NaN,2.5,4.5,0.0
4460,89064,JCI Estacion meteorologica,-62.66325,-60.38959,12.0,WGS84,0.0,132.0,23.0,123.0,...,1.3,1.2,1.5,3.3,NaN,NaN,NaN,2.5,5.1,0.0
4461,89064,JCI Estacion meteorologica,-62.66325,-60.38959,12.0,WGS84,0.0,121.0,12.0,119.0,...,1.2,1.0,1.4,3.0,NaN,NaN,NaN,3.3,4.9,0.0
4462,89064,JCI Estacion meteorologica,-62.66325,-60.38959,12.0,WGS84,0.0,129.0,15.0,110.0,...,1.1,1.1,1.2,2.9,NaN,NaN,NaN,2.6,5.4,0.0
4463,89064,JCI Estacion meteorologica,-62.66325,-60.38959,12.0,WGS84,0.0,128.0,13.0,118.0,...,1.2,1.1,1.2,3.0,NaN,NaN,NaN,2.9,4.8,0.0

In [3]:
try:
    datos_dos = await datos_antartida(
        fecha_inicio="2024-01-01T00:00:00UTC",
        fecha_fin="2024-01-31T23:59:59UTC",
        identificacion=["89064", "89070"],
        api_keys=[API_KEY],
    )
    print(f"Registros combinados (ambas estaciones): {len(datos_dos)}")
    display(pd.DataFrame(datos_dos))
except AemetError as e:
    print(f"Endpoint no disponible: {e}")

Registros combinados (ambas estaciones): 8928

,identificacion,nombre,latitud,longitud,altitud,srs,altNieve,ddd,dddstd,dddx,...,temp,tmn,tmx,ts,tsb,tsmn,tsmx,vel,velx,qdato
0,89064,JCI Estacion meteorologica,-62.66325,-60.38959,12.0,WGS84,NaN,10.0,6.0,9.0,...,1.2,1.2,1.3,3.1,NaN,NaN,NaN,3.6,4.5,0.0
1,89064,JCI Estacion meteorologica,-62.66325,-60.38959,12.0,WGS84,NaN,25.0,6.0,33.0,...,1.2,1.1,1.2,3.0,NaN,NaN,NaN,3.6,4.4,0.0
2,89064,JCI Estacion meteorologica,-62.66325,-60.38959,12.0,WGS84,NaN,29.0,13.0,34.0,...,1.1,1.1,1.2,2.9,NaN,NaN,NaN,2.7,4.1,0.0
3,89064,JCI Estacion meteorologica,-62.66325,-60.38959,12.0,WGS84,NaN,36.0,10.0,22.0,...,1.1,1.1,1.2,2.9,NaN,NaN,NaN,2.4,3.4,0.0
4,89064,JCI Estacion meteorologica,-62.66325,-60.38959,12.0,WGS84,NaN,38.0,11.0,39.0,...,1.1,1.1,1.2,2.8,NaN,NaN,NaN,2.5,3.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8923,89070,GdC Estacion meteorologica,-62.97697,-60.67528,12.0,WGS84,NaN,283.0,10.0,292.0,...,0.9,0.9,1.0,0.9,NaN,NaN,NaN,2.6,3.6,0.0
8924,89070,GdC Estacion meteorologica,-62.97697,-60.67528,12.0,WGS84,NaN,274.0,10.0,286.0,...,0.9,0.9,0.9,0.9,NaN,NaN,NaN,2.2,3.0,0.0
8925,89070,GdC Estacion meteorologica,-62.97697,-60.67528,12.0,WGS84,NaN,262.0,22.0,277.0,...,0.9,0.8,1.1,0.9,NaN,NaN,NaN,2.0,2.8,0.0
8926,89070,GdC Estacion meteorologica,-62.97697,-60.67528,12.0,WGS84,NaN,255.0,22.0,264.0,...,0.8,0.8,1.0,0.9,NaN,NaN,NaN,1.6,2.7,0.0
8927,89070,GdC Estacion meteorologica,-62.97697,-60.67528,12.0,WGS84,NaN,252.0,12.0,258.0,...,0.8,0.7,0.9,0.9,NaN,NaN,NaN,1.5,2.2,0.0

## 2. Maestro de municipios

Catálogo completo de municipios de España. Útil para obtener los códigos necesarios en predicciones.

In [4]:
from aemetdata.maestro import todos_municipios

try:
    municipios = await todos_municipios([API_KEY])
    print(f"Total de municipios en el catalogo: {len(municipios)}")
    df_mun = pd.DataFrame(municipios)
    display(df_mun.head(10))
except AemetError as e:
    print(f"Endpoint no disponible: {e}")
    municipios = []
    df_mun = pd.DataFrame()

httpx disconnect intento 1 para JSON (maestro_municipios), reintentando con urllib: Server disconnected without sending a response.

urllib también falló intento 1 (maestro_municipios): The read operation timed out

httpx disconnect intento 2 para JSON (maestro_municipios), reintentando con urllib: Server disconnected without sending a response.

urllib también falló intento 2 (maestro_municipios): Remote end closed connection without response

httpx disconnect intento 3 para JSON (maestro_municipios), reintentando con urllib: Server disconnected without sending a response.

urllib también falló intento 3 (maestro_municipios): Remote end closed connection without response

Endpoint no disponible: Error descargando JSON (maestro_municipios): Remote end closed connection without response

In [5]:
if not df_mun.empty:
    print("Columnas:", df_mun.columns.tolist())
else:
    print("Sin datos")

Sin datos

In [6]:
from aemetdata.maestro import municipio

try:
    datos_madrid = await municipio("id28079", [API_KEY])
    print("Datos del municipio id28079 (Madrid):")
    display(pd.DataFrame(datos_madrid))
except AemetError as e:
    print(f"Endpoint no disponible: {e}")

httpx disconnect clave 1 [maestro_municipio_id28079], reintentando con urllib: Server disconnected without sending a response.

Error con clave 1 [maestro_municipio_id28079]: Remote end closed connection without response

httpx disconnect clave 1 [maestro_municipio_id28079], reintentando con urllib: Server disconnected without sending a response.

Error con clave 1 [maestro_municipio_id28079]: Remote end closed connection without response

httpx disconnect clave 1 [maestro_municipio_id28079], reintentando con urllib: Server disconnected without sending a response.

Error con clave 1 [maestro_municipio_id28079]: Remote end closed connection without response

httpx disconnect clave 1 [maestro_municipio_id28079], reintentando con urllib: Server disconnected without sending a response.

Error con clave 1 [maestro_municipio_id28079]: Remote end closed connection without response

httpx disconnect clave 1 [maestro_municipio_id28079], reintentando con urllib: Server disconnected without sending a response.

Error con clave 1 [maestro_municipio_id28079]: Remote end closed connection without response

Endpoint no disponible: No se pudo realizar la solicitud 'maestro_municipio_id28079' tras 5 ciclos.

In [7]:
from aemetdata.maestro import municipio_por_nombre

try:
    resultados = await municipio_por_nombre("Sevilla", [API_KEY])
    print(f"Municipios encontrados con 'Sevilla': {len(resultados)}")
    display(pd.DataFrame(resultados))
except AemetError as e:
    print(f"Endpoint no disponible: {e}")

httpx disconnect clave 1 [maestro_municipio_nombre_Sevilla], reintentando con urllib: Server disconnected without sending a response.

Error con clave 1 [maestro_municipio_nombre_Sevilla]: Remote end closed connection without response

httpx disconnect clave 1 [maestro_municipio_nombre_Sevilla], reintentando con urllib: Server disconnected without sending a response.

Error con clave 1 [maestro_municipio_nombre_Sevilla]: Remote end closed connection without response

httpx disconnect clave 1 [maestro_municipio_nombre_Sevilla], reintentando con urllib: Server disconnected without sending a response.

Error con clave 1 [maestro_municipio_nombre_Sevilla]: Remote end closed connection without response

httpx disconnect clave 1 [maestro_municipio_nombre_Sevilla], reintentando con urllib: Server disconnected without sending a response.

Error con clave 1 [maestro_municipio_nombre_Sevilla]: Remote end closed connection without response

httpx disconnect clave 1 [maestro_municipio_nombre_Sevilla], reintentando con urllib: Server disconnected without sending a response.

Error con clave 1 [maestro_municipio_nombre_Sevilla]: Remote end closed connection without response

Endpoint no disponible: No se pudo realizar la solicitud 'maestro_municipio_nombre_Sevilla' tras 5 ciclos.

In [8]:
try:
    barna = await municipio_por_nombre("Barcelona", [API_KEY])
    df_barna = pd.DataFrame(barna)
    print("Resultados para 'Barcelona':")
    print(df_barna.to_string())
except AemetError as e:
    print(f"Endpoint no disponible: {e}")

Error con clave 1 [maestro_municipio_nombre_Barcelona]: Respuesta no JSON: 'text/plain;charset=ISO-8859-15'

Error con clave 1 [maestro_municipio_nombre_Barcelona]: Respuesta no JSON: 'text/plain;charset=ISO-8859-15'

Error con clave 1 [maestro_municipio_nombre_Barcelona]: Respuesta no JSON: 'text/plain;charset=ISO-8859-15'

Error con clave 1 [maestro_municipio_nombre_Barcelona]: Respuesta no JSON: 'text/plain;charset=ISO-8859-15'

Error con clave 1 [maestro_municipio_nombre_Barcelona]: Respuesta no JSON: 'text/plain;charset=ISO-8859-15'

Endpoint no disponible: No se pudo realizar la solicitud 'maestro_municipio_nombre_Barcelona' tras 5 ciclos.